---
version: '3.7'
services:
  sftp:
    image: atmoz/sftp
    volumes:
      - ${PWD}/downloads:/home/foo/downloads
      - ${PWD}/uploads:/home/foo/uploads
    ports:
      - 2222:22
    command: foo:pass:1001