---
# yamllint disable rule:line-length
# yamllint disable rule:comments

- name: get all files in {{ local_path }}
  find:
    paths: "{{ local_path }}"
    recurse: true
    patterns: '*.gz'
  register: compressed

# - name: Unarchive Each File
#   unarchive:
#     src: "{{ item.path }}"
#     dest: "{{ local_path }}"
#   with_items: "{{ compressed.files }}"

- name: Unarchive with GZIP
  shell: gzip -d "{{ item.path }}"
  with_items: "{{ compressed.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Delete archived files
  file:
    state: absent
    path: "{{ item.path }}"
  with_items: "{{ compressed.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: get all files in {{ local_path }}
  find:
    paths: "{{ local_path }}"
    recurse: true
    patterns: '*.csv'
  register: uncompressed

